// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/weir/search/v1/http.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Header preserves one HTTP header name and its ordered values.
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lowercase HTTP header name; the Search adapter validates allowed request names.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Values associated with this header, without folding them into one string.
	Values        []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_api_weir_search_v1_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_search_v1_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_api_weir_search_v1_http_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// HttpRequest is one Search Native request. The selected Store resource names
// the concrete index; the adapter adds that index before this relative HTTP path.
type HttpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP method supported by the adapter for this operation.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Index-relative HTTP path beginning with '/', such as /_bulk or /_doc/id.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Canonically encoded query string without a leading '?'.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// Optional request headers allowed by the Search adapter.
	Headers []*Header `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	// MIME type of body without parameters; required when body is nonempty.
	BodyContentType string `protobuf:"bytes,5,opt,name=body_content_type,json=bodyContentType,proto3" json:"body_content_type,omitempty"`
	// Complete request body, at most 8 MiB, supplied independently of HTTP framing.
	Body          []byte `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_api_weir_search_v1_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_search_v1_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_search_v1_http_proto_rawDescGZIP(), []int{1}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBodyContentType() string {
	if x != nil {
		return x.BodyContentType
	}
	return ""
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HttpResponse is the Search Native response metadata.
// HTTP status is preserved independently of the NativeEnd transport evidence.
type HttpResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original backend HTTP status code, including non-success responses.
	StatusCode uint32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Backend response headers that can be represented by the Native adapter.
	Headers       []*Header `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_api_weir_search_v1_http_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_search_v1_http_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_api_weir_search_v1_http_proto_rawDescGZIP(), []int{2}
}

func (x *HttpResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_api_weir_search_v1_http_proto protoreflect.FileDescriptor

const file_api_weir_search_v1_http_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/weir/search/v1/http.proto\x12\x0eweir.search.v1\"4\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\xc1\x01\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x120\n" +
	"\aheaders\x18\x04 \x03(\v2\x16.weir.search.v1.HeaderR\aheaders\x12*\n" +
	"\x11body_content_type\x18\x05 \x01(\tR\x0fbodyContentType\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\"a\n" +
	"\fHttpResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x120\n" +
	"\aheaders\x18\x02 \x03(\v2\x16.weir.search.v1.HeaderR\aheadersBBZ@github.com/batchstream/weir-protocol/api/weir/search/v1;searchv1b\x06proto3"

var (
	file_api_weir_search_v1_http_proto_rawDescOnce sync.Once
	file_api_weir_search_v1_http_proto_rawDescData []byte
)

func file_api_weir_search_v1_http_proto_rawDescGZIP() []byte {
	file_api_weir_search_v1_http_proto_rawDescOnce.Do(func() {
		file_api_weir_search_v1_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_weir_search_v1_http_proto_rawDesc), len(file_api_weir_search_v1_http_proto_rawDesc)))
	})
	return file_api_weir_search_v1_http_proto_rawDescData
}

var file_api_weir_search_v1_http_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_weir_search_v1_http_proto_goTypes = []any{
	(*Header)(nil),       // 0: weir.search.v1.Header
	(*HttpRequest)(nil),  // 1: weir.search.v1.HttpRequest
	(*HttpResponse)(nil), // 2: weir.search.v1.HttpResponse
}
var file_api_weir_search_v1_http_proto_depIdxs = []int32{
	0, // 0: weir.search.v1.HttpRequest.headers:type_name -> weir.search.v1.Header
	0, // 1: weir.search.v1.HttpResponse.headers:type_name -> weir.search.v1.Header
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_weir_search_v1_http_proto_init() }
func file_api_weir_search_v1_http_proto_init() {
	if File_api_weir_search_v1_http_proto != nil {
		return
	}
	type x struct{}
	packageMarker := x{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(packageMarker).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_weir_search_v1_http_proto_rawDesc), len(file_api_weir_search_v1_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_weir_search_v1_http_proto_goTypes,
		DependencyIndexes: file_api_weir_search_v1_http_proto_depIdxs,
		MessageInfos:      file_api_weir_search_v1_http_proto_msgTypes,
	}.Build()
	File_api_weir_search_v1_http_proto = out.File
	file_api_weir_search_v1_http_proto_goTypes = nil
	file_api_weir_search_v1_http_proto_depIdxs = nil
}
