// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: api/weir/v1/store.proto

package weirv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_ResolveStore_FullMethodName = "/weir.v1.StoreService/ResolveStore"
	StoreService_Read_FullMethodName         = "/weir.v1.StoreService/Read"
	StoreService_Mutate_FullMethodName       = "/weir.v1.StoreService/Mutate"
	StoreService_Execute_FullMethodName      = "/weir.v1.StoreService/Execute"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StoreService discovers Store endpoints and executes requests on their owners.
// Initialize through ResolveStore, then connect directly to a returned endpoint.
type StoreServiceClient interface {
	// ResolveStore returns the current endpoints for one configured Store.
	ResolveStore(ctx context.Context, in *ResolveStoreRequest, opts ...grpc.CallOption) (*ResolveStoreResponse, error)
	// Read validates the entire batch before execution and preserves input order.
	// Missing documents and backend failures are reported separately for each item.
	Read(ctx context.Context, in *ReadBatchRequest, opts ...grpc.CallOption) (*ReadBatchResponse, error)
	// Mutate validates the entire batch before executing independent mutations.
	// Mutations to one resource run in input order, including after item failures;
	// different resources may run concurrently. A batch is not a transaction.
	// Across RPCs, ordering follows the database semantics. Never replay mutations
	// automatically: a failed RPC cannot prove that its mutations were not applied.
	Mutate(ctx context.Context, in *MutateBatchRequest, opts ...grpc.CallOption) (*MutateBatchResponse, error)
	// Execute runs one finite Scan or Native request and streams typed events.
	// A Scan checkpoint is usable only after its terminal event and final gRPC OK.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	client := &storeServiceClient{cc}
	return client
}

func (c *storeServiceClient) ResolveStore(ctx context.Context, in *ResolveStoreRequest, opts ...grpc.CallOption) (*ResolveStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveStoreResponse)
	err := c.cc.Invoke(ctx, StoreService_ResolveStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Read(ctx context.Context, in *ReadBatchRequest, opts ...grpc.CallOption) (*ReadBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadBatchResponse)
	err := c.cc.Invoke(ctx, StoreService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Mutate(ctx context.Context, in *MutateBatchRequest, opts ...grpc.CallOption) (*MutateBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateBatchResponse)
	err := c.cc.Invoke(ctx, StoreService_Mutate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[0], StoreService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_ExecuteClient = grpc.ServerStreamingClient[ExecuteResponse]

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
//
// StoreService discovers Store endpoints and executes requests on their owners.
// Initialize through ResolveStore, then connect directly to a returned endpoint.
type StoreServiceServer interface {
	// ResolveStore returns the current endpoints for one configured Store.
	ResolveStore(context.Context, *ResolveStoreRequest) (*ResolveStoreResponse, error)
	// Read validates the entire batch before execution and preserves input order.
	// Missing documents and backend failures are reported separately for each item.
	Read(context.Context, *ReadBatchRequest) (*ReadBatchResponse, error)
	// Mutate validates the entire batch before executing independent mutations.
	// Mutations to one resource run in input order, including after item failures;
	// different resources may run concurrently. A batch is not a transaction.
	// Across RPCs, ordering follows the database semantics. Never replay mutations
	// automatically: a failed RPC cannot prove that its mutations were not applied.
	Mutate(context.Context, *MutateBatchRequest) (*MutateBatchResponse, error)
	// Execute runs one finite Scan or Native request and streams typed events.
	// A Scan checkpoint is usable only after its terminal event and final gRPC OK.
	Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) ResolveStore(context.Context, *ResolveStoreRequest) (*ResolveStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveStore not implemented")
}
func (UnimplementedStoreServiceServer) Read(context.Context, *ReadBatchRequest) (*ReadBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedStoreServiceServer) Mutate(context.Context, *MutateBatchRequest) (*MutateBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mutate not implemented")
}
func (UnimplementedStoreServiceServer) Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_ResolveStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ResolveStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ResolveStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ResolveStore(ctx, req.(*ResolveStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Read(ctx, req.(*ReadBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_Mutate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Mutate(ctx, req.(*MutateBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	serverStream := &grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream}
	return srv.(StoreServiceServer).Execute(m, serverStream)
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_ExecuteServer = grpc.ServerStreamingServer[ExecuteResponse]

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weir.v1.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveStore",
			Handler:    _StoreService_ResolveStore_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _StoreService_Read_Handler,
		},
		{
			MethodName: "Mutate",
			Handler:    _StoreService_Mutate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _StoreService_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/weir/v1/store.proto",
}
