// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/weir/v1/store.proto

package weirv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FailureCode classifies operation failures independently of backend error types.
// Future positive codes are opaque generic failures. Clients retain the numeric
// code and separate application/transport evidence without inferring retry safety.
type FailureCode int32

const (
	// Unset value; invalid in a reported Failure.
	FailureCode_FAILURE_CODE_UNSPECIFIED FailureCode = 0
	// Input violates the request or adapter contract.
	FailureCode_INVALID_ARGUMENT FailureCode = 1
	// Required authentication could not be established.
	FailureCode_UNAUTHENTICATED FailureCode = 2
	// The caller or configured backend identity lacks access.
	FailureCode_PERMISSION_DENIED FailureCode = 3
	// The required adapter-owned target does not exist. A missing document
	// is a successful ReadResult.missing or a mutation precondition failure.
	FailureCode_TARGET_NOT_FOUND FailureCode = 4
	// The target does not satisfy an operation precondition.
	FailureCode_PRECONDITION_FAILED FailureCode = 5
	// A conflicting concurrent operation prevented this operation.
	FailureCode_CONFLICT FailureCode = 6
	// The adapter does not support the requested operation or option.
	FailureCode_UNSUPPORTED FailureCode = 7
	// An input, output, or execution budget was exceeded.
	FailureCode_RESOURCE_EXHAUSTED FailureCode = 8
	// A required service or transport is unavailable.
	FailureCode_UNAVAILABLE FailureCode = 9
	// The request was cancelled.
	FailureCode_CANCELLED FailureCode = 10
	// The request's deadline expired.
	FailureCode_DEADLINE_EXCEEDED FailureCode = 11
	// An execution or response invariant failed.
	FailureCode_INTERNAL FailureCode = 12
)

// Enum value maps for FailureCode.
var (
	FailureCode_name = map[int32]string{
		0:  "FAILURE_CODE_UNSPECIFIED",
		1:  "INVALID_ARGUMENT",
		2:  "UNAUTHENTICATED",
		3:  "PERMISSION_DENIED",
		4:  "TARGET_NOT_FOUND",
		5:  "PRECONDITION_FAILED",
		6:  "CONFLICT",
		7:  "UNSUPPORTED",
		8:  "RESOURCE_EXHAUSTED",
		9:  "UNAVAILABLE",
		10: "CANCELLED",
		11: "DEADLINE_EXCEEDED",
		12: "INTERNAL",
	}
	FailureCode_value = map[string]int32{
		"FAILURE_CODE_UNSPECIFIED": 0,
		"INVALID_ARGUMENT":         1,
		"UNAUTHENTICATED":          2,
		"PERMISSION_DENIED":        3,
		"TARGET_NOT_FOUND":         4,
		"PRECONDITION_FAILED":      5,
		"CONFLICT":                 6,
		"UNSUPPORTED":              7,
		"RESOURCE_EXHAUSTED":       8,
		"UNAVAILABLE":              9,
		"CANCELLED":                10,
		"DEADLINE_EXCEEDED":        11,
		"INTERNAL":                 12,
	}
)

func (x FailureCode) Enum() *FailureCode {
	p := new(FailureCode)
	*p = x
	return p
}

func (x FailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_weir_v1_store_proto_enumTypes[0].Descriptor()
}

func (FailureCode) Type() protoreflect.EnumType {
	return &file_api_weir_v1_store_proto_enumTypes[0]
}

func (x FailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureCode.Descriptor instead.
func (FailureCode) EnumDescriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{0}
}

// MutationOutcome describes application evidence, not whether an error occurred.
// Its vocabulary is fixed; unknown values are invalid completion evidence.
type MutationOutcome int32

const (
	// Unset value; invalid in a reported MutationResult.
	MutationOutcome_MUTATION_OUTCOME_UNSPECIFIED MutationOutcome = 0
	// The mutation was not started against the backend.
	MutationOutcome_NOT_STARTED MutationOutcome = 1
	// Execution established that the mutation was not applied.
	MutationOutcome_NOT_APPLIED MutationOutcome = 2
	// Execution established that the requested semantics were satisfied, including
	// a successful no-op such as deleting a document that was already absent.
	MutationOutcome_APPLIED MutationOutcome = 3
	// Available evidence cannot establish whether the mutation was applied.
	MutationOutcome_UNKNOWN MutationOutcome = 4
)

// Enum value maps for MutationOutcome.
var (
	MutationOutcome_name = map[int32]string{
		0: "MUTATION_OUTCOME_UNSPECIFIED",
		1: "NOT_STARTED",
		2: "NOT_APPLIED",
		3: "APPLIED",
		4: "UNKNOWN",
	}
	MutationOutcome_value = map[string]int32{
		"MUTATION_OUTCOME_UNSPECIFIED": 0,
		"NOT_STARTED":                  1,
		"NOT_APPLIED":                  2,
		"APPLIED":                      3,
		"UNKNOWN":                      4,
	}
)

func (x MutationOutcome) Enum() *MutationOutcome {
	p := new(MutationOutcome)
	*p = x
	return p
}

func (x MutationOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_api_weir_v1_store_proto_enumTypes[1].Descriptor()
}

func (MutationOutcome) Type() protoreflect.EnumType {
	return &file_api_weir_v1_store_proto_enumTypes[1]
}

func (x MutationOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationOutcome.Descriptor instead.
func (MutationOutcome) EnumDescriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{1}
}

// ProjectionMode selects one uniform field selection rule.
type ProjectionMode int32

const (
	// Unset value; invalid in an explicit Projection.
	ProjectionMode_PROJECTION_MODE_UNSPECIFIED ProjectionMode = 0
	// Return only the selected fields.
	ProjectionMode_INCLUDE ProjectionMode = 1
	// Return all fields except the selected fields.
	ProjectionMode_EXCLUDE ProjectionMode = 2
)

// Enum value maps for ProjectionMode.
var (
	ProjectionMode_name = map[int32]string{
		0: "PROJECTION_MODE_UNSPECIFIED",
		1: "INCLUDE",
		2: "EXCLUDE",
	}
	ProjectionMode_value = map[string]int32{
		"PROJECTION_MODE_UNSPECIFIED": 0,
		"INCLUDE":                     1,
		"EXCLUDE":                     2,
	}
)

func (x ProjectionMode) Enum() *ProjectionMode {
	p := new(ProjectionMode)
	*p = x
	return p
}

func (x ProjectionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_weir_v1_store_proto_enumTypes[2].Descriptor()
}

func (ProjectionMode) Type() protoreflect.EnumType {
	return &file_api_weir_v1_store_proto_enumTypes[2]
}

func (x ProjectionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectionMode.Descriptor instead.
func (ProjectionMode) EnumDescriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{2}
}

// NativeCompletion reports response transport evidence, never mutation outcomes.
// Its vocabulary is fixed; unknown values are invalid completion evidence.
type NativeCompletion int32

const (
	// Unset value; invalid in a reported NativeEnd.
	NativeCompletion_NATIVE_COMPLETION_UNSPECIFIED NativeCompletion = 0
	// The native operation was not started against the backend.
	NativeCompletion_NATIVE_NOT_STARTED NativeCompletion = 1
	// The native response was received completely.
	NativeCompletion_RESPONSE_COMPLETE NativeCompletion = 2
	// The native operation started but its response was not received completely.
	NativeCompletion_RESPONSE_INCOMPLETE NativeCompletion = 3
)

// Enum value maps for NativeCompletion.
var (
	NativeCompletion_name = map[int32]string{
		0: "NATIVE_COMPLETION_UNSPECIFIED",
		1: "NATIVE_NOT_STARTED",
		2: "RESPONSE_COMPLETE",
		3: "RESPONSE_INCOMPLETE",
	}
	NativeCompletion_value = map[string]int32{
		"NATIVE_COMPLETION_UNSPECIFIED": 0,
		"NATIVE_NOT_STARTED":            1,
		"RESPONSE_COMPLETE":             2,
		"RESPONSE_INCOMPLETE":           3,
	}
)

func (x NativeCompletion) Enum() *NativeCompletion {
	p := new(NativeCompletion)
	*p = x
	return p
}

func (x NativeCompletion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NativeCompletion) Descriptor() protoreflect.EnumDescriptor {
	return file_api_weir_v1_store_proto_enumTypes[3].Descriptor()
}

func (NativeCompletion) Type() protoreflect.EnumType {
	return &file_api_weir_v1_store_proto_enumTypes[3]
}

func (x NativeCompletion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NativeCompletion.Descriptor instead.
func (NativeCompletion) EnumDescriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{3}
}

// ResolveStoreRequest selects the Store whose owner endpoints are required.
type ResolveStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configured Store name, independent of the deployment platform.
	StoreName     string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveStoreRequest) Reset() {
	*x = ResolveStoreRequest{}
	mi := &file_api_weir_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveStoreRequest) ProtoMessage() {}

func (x *ResolveStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveStoreRequest.ProtoReflect.Descriptor instead.
func (*ResolveStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveStoreRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

// ResolveStoreResponse supplies addresses for direct execution connections.
type ResolveStoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Store selected by the request.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// Portable IP or DNS host:port addresses. DNS may identify several replicas.
	Endpoints []string `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Maximum client cache lifetime for this endpoint set, in milliseconds.
	CacheTtlMs    uint64 `protobuf:"varint,3,opt,name=cache_ttl_ms,json=cacheTtlMs,proto3" json:"cache_ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveStoreResponse) Reset() {
	*x = ResolveStoreResponse{}
	mi := &file_api_weir_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveStoreResponse) ProtoMessage() {}

func (x *ResolveStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveStoreResponse.ProtoReflect.Descriptor instead.
func (*ResolveStoreResponse) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveStoreResponse) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *ResolveStoreResponse) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ResolveStoreResponse) GetCacheTtlMs() uint64 {
	if x != nil {
		return x.CacheTtlMs
	}
	return 0
}

// ExecuteRequest binds one bounded operation to its owning Store and index.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Store that owns all resources; must remain identical throughout the stream.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// Consecutive one-based record ordinal. Each Read or Mutate request advances
	// it by one. Scan and Native always use 1. UINT64_MAX is invalid.
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Required operation; its kind must remain identical throughout the stream.
	Command       *Command `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_weir_v1_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *ExecuteRequest) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ExecuteRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// ExecuteResponse carries one bounded result or streaming event.
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One-based input record ordinal; record results arrive in input order.
	// Every input record has exactly one result. Scan and Native events all use 1.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Required typed event; it must match the stream's operation kind.
	Event         *Event `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_weir_v1_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ExecuteResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// Command selects one bounded operation with incrementally delivered results.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one operation is required.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*Command_Read
	//	*Command_Mutate
	//	*Command_Scan
	//	*Command_Native
	Operation     isCommand_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_weir_v1_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetOperation() isCommand_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Command) GetRead() *ReadRequest {
	if x != nil {
		if x, ok := x.Operation.(*Command_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Command) GetMutate() *MutateRequest {
	if x != nil {
		if x, ok := x.Operation.(*Command_Mutate); ok {
			return x.Mutate
		}
	}
	return nil
}

func (x *Command) GetScan() *ScanRequest {
	if x != nil {
		if x, ok := x.Operation.(*Command_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

func (x *Command) GetNative() *NativeRequest {
	if x != nil {
		if x, ok := x.Operation.(*Command_Native); ok {
			return x.Native
		}
	}
	return nil
}

type isCommand_Operation interface {
	isCommand_Operation()
}

type Command_Read struct {
	// Read one resource and return its indexed ReadResult.
	Read *ReadRequest `protobuf:"bytes,1,opt,name=read,proto3,oneof"`
}

type Command_Mutate struct {
	// Mutate one resource and return its indexed MutationResult.
	Mutate *MutateRequest `protobuf:"bytes,2,opt,name=mutate,proto3,oneof"`
}

type Command_Scan struct {
	// Read one bounded traversal page.
	Scan *ScanRequest `protobuf:"bytes,3,opt,name=scan,proto3,oneof"`
}

type Command_Native struct {
	// Execute an adapter-owned operation with an opaque request body.
	Native *NativeRequest `protobuf:"bytes,4,opt,name=native,proto3,oneof"`
}

func (*Command_Read) isCommand_Operation() {}

func (*Command_Mutate) isCommand_Operation() {}

func (*Command_Scan) isCommand_Operation() {}

func (*Command_Native) isCommand_Operation() {}

// NativeRequest supplies an adapter-owned operation with its complete input.
type NativeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical target path relative to the selected Store.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Required opaque request document, with at most 8 MiB of payload bytes.
	// The adapter interprets content_type and data; empty data is permitted.
	Request       *Document `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeRequest) Reset() {
	*x = NativeRequest{}
	mi := &file_api_weir_v1_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeRequest) ProtoMessage() {}

func (x *NativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeRequest.ProtoReflect.Descriptor instead.
func (*NativeRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{5}
}

func (x *NativeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *NativeRequest) GetRequest() *Document {
	if x != nil {
		return x.Request
	}
	return nil
}

// Event is a per-record result, Scan document/end, or Native head/body/end event.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one event value is required.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Event_ReadResult
	//	*Event_MutationResult
	//	*Event_Document
	//	*Event_Head
	//	*Event_Chunk
	//	*Event_ScanEnd
	//	*Event_NativeEnd
	Value         isEvent_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_weir_v1_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetValue() isEvent_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Event) GetReadResult() *ReadResult {
	if x != nil {
		if x, ok := x.Value.(*Event_ReadResult); ok {
			return x.ReadResult
		}
	}
	return nil
}

func (x *Event) GetMutationResult() *MutationResult {
	if x != nil {
		if x, ok := x.Value.(*Event_MutationResult); ok {
			return x.MutationResult
		}
	}
	return nil
}

func (x *Event) GetDocument() *Document {
	if x != nil {
		if x, ok := x.Value.(*Event_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *Event) GetHead() *NativeHead {
	if x != nil {
		if x, ok := x.Value.(*Event_Head); ok {
			return x.Head
		}
	}
	return nil
}

func (x *Event) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Value.(*Event_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *Event) GetScanEnd() *ScanEnd {
	if x != nil {
		if x, ok := x.Value.(*Event_ScanEnd); ok {
			return x.ScanEnd
		}
	}
	return nil
}

func (x *Event) GetNativeEnd() *NativeEnd {
	if x != nil {
		if x, ok := x.Value.(*Event_NativeEnd); ok {
			return x.NativeEnd
		}
	}
	return nil
}

type isEvent_Value interface {
	isEvent_Value()
}

type Event_ReadResult struct {
	// Result for the ReadRequest identified by ExecuteResponse.index.
	ReadResult *ReadResult `protobuf:"bytes,1,opt,name=read_result,json=readResult,proto3,oneof"`
}

type Event_MutationResult struct {
	// Application evidence for the MutateRequest identified by the response index.
	MutationResult *MutationResult `protobuf:"bytes,2,opt,name=mutation_result,json=mutationResult,proto3,oneof"`
}

type Event_Document struct {
	// Next document in the current Scan page.
	Document *Document `protobuf:"bytes,3,opt,name=document,proto3,oneof"`
}

type Event_Head struct {
	// Native response metadata, delivered before response body chunks.
	Head *NativeHead `protobuf:"bytes,4,opt,name=head,proto3,oneof"`
}

type Event_Chunk struct {
	// Nonempty opaque fragment of the Native response body.
	Chunk []byte `protobuf:"bytes,5,opt,name=chunk,proto3,oneof"`
}

type Event_ScanEnd struct {
	// Terminal Scan evidence and an optional successful continuation.
	ScanEnd *ScanEnd `protobuf:"bytes,6,opt,name=scan_end,json=scanEnd,proto3,oneof"`
}

type Event_NativeEnd struct {
	// Terminal evidence of Native response transport completion.
	NativeEnd *NativeEnd `protobuf:"bytes,7,opt,name=native_end,json=nativeEnd,proto3,oneof"`
}

func (*Event_ReadResult) isEvent_Value() {}

func (*Event_MutationResult) isEvent_Value() {}

func (*Event_Document) isEvent_Value() {}

func (*Event_Head) isEvent_Value() {}

func (*Event_Chunk) isEvent_Value() {}

func (*Event_ScanEnd) isEvent_Value() {}

func (*Event_NativeEnd) isEvent_Value() {}

// Empty is an explicit marker for a missing document or a delete action.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_weir_v1_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{7}
}

// Document binds opaque bytes to an explicit content type; adapters own their format.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required MIME media type without parameters.
	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Payload bytes, bounded separately from the enclosing protobuf message.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_weir_v1_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{8}
}

func (x *Document) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Document) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Failure carries one bounded, readable description of an operation failure.
type Failure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required positive failure classification; unknown positive values are valid.
	Code FailureCode `protobuf:"varint,1,opt,name=code,proto3,enum=weir.v1.FailureCode" json:"code,omitempty"`
	// UTF-8 diagnostic text; clients must use code for programmatic decisions.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_api_weir_v1_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{9}
}

func (x *Failure) GetCode() FailureCode {
	if x != nil {
		return x.Code
	}
	return FailureCode_FAILURE_CODE_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReadRequest reads one document using the owning adapter's resource grammar.
type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical path relative to the selected Store; no scheme or leading slash.
	Resource      string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_api_weir_v1_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{10}
}

func (x *ReadRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

// ReadResult distinguishes a returned document, absence, and an execution failure.
type ReadResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one result is required.
	//
	// Types that are valid to be assigned to Result:
	//
	//	*ReadResult_Document
	//	*ReadResult_Missing
	//	*ReadResult_Failure
	Result        isReadResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResult) Reset() {
	*x = ReadResult{}
	mi := &file_api_weir_v1_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResult) ProtoMessage() {}

func (x *ReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResult.ProtoReflect.Descriptor instead.
func (*ReadResult) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{11}
}

func (x *ReadResult) GetResult() isReadResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReadResult) GetDocument() *Document {
	if x != nil {
		if x, ok := x.Result.(*ReadResult_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *ReadResult) GetMissing() *Empty {
	if x != nil {
		if x, ok := x.Result.(*ReadResult_Missing); ok {
			return x.Missing
		}
	}
	return nil
}

func (x *ReadResult) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Result.(*ReadResult_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isReadResult_Result interface {
	isReadResult_Result()
}

type ReadResult_Document struct {
	// The requested document was found.
	Document *Document `protobuf:"bytes,1,opt,name=document,proto3,oneof"`
}

type ReadResult_Missing struct {
	// The read succeeded and the requested document does not exist.
	Missing *Empty `protobuf:"bytes,2,opt,name=missing,proto3,oneof"`
}

type ReadResult_Failure struct {
	// The read could not produce a document or reliable absence evidence.
	Failure *Failure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*ReadResult_Document) isReadResult_Result() {}

func (*ReadResult_Missing) isReadResult_Result() {}

func (*ReadResult_Failure) isReadResult_Result() {}

// MutateRequest applies one action to one resource using adapter-owned semantics.
type MutateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical path relative to the selected Store; no scheme or leading slash.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Exactly one mutation action is required.
	//
	// Types that are valid to be assigned to Action:
	//
	//	*MutateRequest_Put
	//	*MutateRequest_Create
	//	*MutateRequest_Replace
	//	*MutateRequest_Delete
	//	*MutateRequest_AtomicTransform
	Action        isMutateRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRequest) Reset() {
	*x = MutateRequest{}
	mi := &file_api_weir_v1_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRequest) ProtoMessage() {}

func (x *MutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRequest.ProtoReflect.Descriptor instead.
func (*MutateRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{12}
}

func (x *MutateRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *MutateRequest) GetAction() isMutateRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *MutateRequest) GetPut() *Document {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *MutateRequest) GetCreate() *Document {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *MutateRequest) GetReplace() *Document {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_Replace); ok {
			return x.Replace
		}
	}
	return nil
}

func (x *MutateRequest) GetDelete() *Empty {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *MutateRequest) GetAtomicTransform() *Transform {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_AtomicTransform); ok {
			return x.AtomicTransform
		}
	}
	return nil
}

type isMutateRequest_Action interface {
	isMutateRequest_Action()
}

type MutateRequest_Put struct {
	// Create or replace the resource with this document.
	Put *Document `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type MutateRequest_Create struct {
	// Create the resource only when it does not already exist.
	Create *Document `protobuf:"bytes,3,opt,name=create,proto3,oneof"`
}

type MutateRequest_Replace struct {
	// Replace an existing resource with this document.
	Replace *Document `protobuf:"bytes,4,opt,name=replace,proto3,oneof"`
}

type MutateRequest_Delete struct {
	// Delete the resource.
	Delete *Empty `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type MutateRequest_AtomicTransform struct {
	// Apply Lua source or a backend expression atomically to the resource.
	AtomicTransform *Transform `protobuf:"bytes,6,opt,name=atomic_transform,json=atomicTransform,proto3,oneof"`
}

func (*MutateRequest_Put) isMutateRequest_Action() {}

func (*MutateRequest_Create) isMutateRequest_Action() {}

func (*MutateRequest_Replace) isMutateRequest_Action() {}

func (*MutateRequest_Delete) isMutateRequest_Action() {}

func (*MutateRequest_AtomicTransform) isMutateRequest_Action() {}

// MutationResult reports the known application outcome and any associated failure.
type MutationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required application evidence; UNKNOWN must never trigger automatic replay.
	Outcome MutationOutcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=weir.v1.MutationOutcome" json:"outcome,omitempty"`
	// Required unless APPLIED. APPLIED may still report an acknowledgement failure.
	Failure       *Failure `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationResult) Reset() {
	*x = MutationResult{}
	mi := &file_api_weir_v1_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResult) ProtoMessage() {}

func (x *MutationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResult.ProtoReflect.Descriptor instead.
func (*MutationResult) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{13}
}

func (x *MutationResult) GetOutcome() MutationOutcome {
	if x != nil {
		return x.Outcome
	}
	return MutationOutcome_MUTATION_OUTCOME_UNSPECIFIED
}

func (x *MutationResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

// Transform selects Lua or a native backend expression for one atomic mutation.
type Transform struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one transform form is required.
	//
	// Types that are valid to be assigned to Form:
	//
	//	*Transform_Lua
	//	*Transform_BackendExpression
	Form          isTransform_Form `protobuf_oneof:"form"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transform) Reset() {
	*x = Transform{}
	mi := &file_api_weir_v1_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{14}
}

func (x *Transform) GetForm() isTransform_Form {
	if x != nil {
		return x.Form
	}
	return nil
}

func (x *Transform) GetLua() *LuaTransform {
	if x != nil {
		if x, ok := x.Form.(*Transform_Lua); ok {
			return x.Lua
		}
	}
	return nil
}

func (x *Transform) GetBackendExpression() *Document {
	if x != nil {
		if x, ok := x.Form.(*Transform_BackendExpression); ok {
			return x.BackendExpression
		}
	}
	return nil
}

type isTransform_Form interface {
	isTransform_Form()
}

type Transform_Lua struct {
	// Lua operating on the current document or nil when absent.
	Lua *LuaTransform `protobuf:"bytes,1,opt,name=lua,proto3,oneof"`
}

type Transform_BackendExpression struct {
	// Opaque expression interpreted and validated by the backend adapter.
	BackendExpression *Document `protobuf:"bytes,2,opt,name=backend_expression,json=backendExpression,proto3,oneof"`
}

func (*Transform_Lua) isTransform_Form() {}

func (*Transform_BackendExpression) isTransform_Form() {}

// LuaTransform supplies source code and optional input with Lua 5.4 semantics.
// Source returns one function(current, incoming), using ordinary document tables.
// Missing current or omitted Input is nil. The callback returns exactly one
// object to replace/create, or weir.keep(), weir.delete(), or weir.reject(message).
// Keep/delete on a missing document are successful no-ops; reject is
// NOT_APPLIED/PRECONDITION_FAILED. Nil, arrays, scalars, and missing/multiple
// callback returns are invalid. A callback error or invalid result never writes.
// Null is weir.null(); object/array tables and exact signed 64-bit integers retain
// their document kinds. Helpers and conversion rules are part of this contract.
// Source, entry point, return actions, and Lua semantics have no runtime selector.
type LuaTransform struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nonempty UTF-8 source code; precompiled bytecode is not accepted.
	Source []byte `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Optional input document made available to the program.
	Input         *Document `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuaTransform) Reset() {
	*x = LuaTransform{}
	mi := &file_api_weir_v1_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuaTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuaTransform) ProtoMessage() {}

func (x *LuaTransform) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuaTransform.ProtoReflect.Descriptor instead.
func (*LuaTransform) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{15}
}

func (x *LuaTransform) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LuaTransform) GetInput() *Document {
	if x != nil {
		return x.Input
	}
	return nil
}

// Projection selects bounded, distinct dot-separated field paths. Duplicate
// paths and overlapping ancestor/descendant paths are invalid.
type Projection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required INCLUDE or EXCLUDE mode; mixing modes within one request is invalid.
	Mode ProjectionMode `protobuf:"varint,1,opt,name=mode,proto3,enum=weir.v1.ProjectionMode" json:"mode,omitempty"`
	// 1-128 paths, at most 512 bytes each and 8 KiB encoded Projection total;
	// no wildcard characters, control characters, or empty segments.
	Fields        []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Projection) Reset() {
	*x = Projection{}
	mi := &file_api_weir_v1_store_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Projection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projection) ProtoMessage() {}

func (x *Projection) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projection.ProtoReflect.Descriptor instead.
func (*Projection) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{16}
}

func (x *Projection) GetMode() ProjectionMode {
	if x != nil {
		return x.Mode
	}
	return ProjectionMode_PROJECTION_MODE_UNSPECIFIED
}

func (x *Projection) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ScanRequest reads one finite page from an adapter-owned ordered traversal.
// Scan is read-only and returns documents without independent resource identity.
// Continuations bind Store, backend profile, resource, filter, and projection;
// page_size may change. MongoDB provides no cross-page snapshot and no imposed
// token expiry. Search uses a backend PIT with 60s validity, refreshed by requests.
// A failed/expired continuation must fail; clients must not restart automatically.
type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical traversal target path relative to the selected Store.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Optional adapter-owned filter expression, with at most 16 KiB of payload bytes.
	// The adapter interprets its content type and data; absent selects all documents.
	Filter *Document `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional explicit field selection. Absent returns complete documents.
	Projection *Projection `protobuf:"bytes,3,opt,name=projection,proto3" json:"projection,omitempty"`
	// Maximum documents in this page. Zero uses 128; the maximum is 256.
	PageSize uint32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque versioned checkpoint from a completed page, portable across nodes
	// serving the same Store with an equivalent backend configuration. During a
	// rolling upgrade, readers retain its format for the advertised validity.
	// Tokens detect corruption only; they are not authentication or authorization.
	ContinuationToken []byte `protobuf:"bytes,5,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_api_weir_v1_store_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{17}
}

func (x *ScanRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ScanRequest) GetFilter() *Document {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ScanRequest) GetProjection() *Projection {
	if x != nil {
		return x.Projection
	}
	return nil
}

func (x *ScanRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ScanRequest) GetContinuationToken() []byte {
	if x != nil {
		return x.ContinuationToken
	}
	return nil
}

// ScanEnd closes one finite page. A successful page has exactly one of exhausted
// or next_continuation_token. Accept its checkpoint only after the document count
// matches the received events and the RPC completes with final gRPC OK (EOF).
type ScanEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of document events emitted in this page, including a failed page.
	DocumentCount uint64 `protobuf:"varint,1,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	// Optional terminal failure; failed pages provide no successful checkpoint.
	Failure *Failure `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	// Opaque next-page checkpoint; present only on nonexhausted successful pages.
	NextContinuationToken []byte `protobuf:"bytes,3,opt,name=next_continuation_token,json=nextContinuationToken,proto3" json:"next_continuation_token,omitempty"`
	// True only when a successful traversal has reached its end.
	Exhausted     bool `protobuf:"varint,4,opt,name=exhausted,proto3" json:"exhausted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanEnd) Reset() {
	*x = ScanEnd{}
	mi := &file_api_weir_v1_store_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanEnd) ProtoMessage() {}

func (x *ScanEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanEnd.ProtoReflect.Descriptor instead.
func (*ScanEnd) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{18}
}

func (x *ScanEnd) GetDocumentCount() uint64 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *ScanEnd) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *ScanEnd) GetNextContinuationToken() []byte {
	if x != nil {
		return x.NextContinuationToken
	}
	return nil
}

func (x *ScanEnd) GetExhausted() bool {
	if x != nil {
		return x.Exhausted
	}
	return false
}

// NativeHead describes the native response before any body chunks are delivered.
type NativeHead struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional adapter-owned response metadata, with at most 64 KiB of payload bytes.
	// Its content type and bytes are opaque to the public protocol.
	Metadata *Document `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// MIME type of following body chunks; empty when no type was supplied.
	BodyContentType string `protobuf:"bytes,2,opt,name=body_content_type,json=bodyContentType,proto3" json:"body_content_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NativeHead) Reset() {
	*x = NativeHead{}
	mi := &file_api_weir_v1_store_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeHead) ProtoMessage() {}

func (x *NativeHead) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeHead.ProtoReflect.Descriptor instead.
func (*NativeHead) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{19}
}

func (x *NativeHead) GetMetadata() *Document {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NativeHead) GetBodyContentType() string {
	if x != nil {
		return x.BodyContentType
	}
	return ""
}

// NativeEnd closes the response transport and reports any incomplete exchange.
type NativeEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required completion evidence; it does not prove whether writes were applied.
	Completion NativeCompletion `protobuf:"varint,1,opt,name=completion,proto3,enum=weir.v1.NativeCompletion" json:"completion,omitempty"`
	// Required unless RESPONSE_COMPLETE; complete responses have no transport failure.
	Failure       *Failure `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeEnd) Reset() {
	*x = NativeEnd{}
	mi := &file_api_weir_v1_store_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeEnd) ProtoMessage() {}

func (x *NativeEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_store_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeEnd.ProtoReflect.Descriptor instead.
func (*NativeEnd) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_store_proto_rawDescGZIP(), []int{20}
}

func (x *NativeEnd) GetCompletion() NativeCompletion {
	if x != nil {
		return x.Completion
	}
	return NativeCompletion_NATIVE_COMPLETION_UNSPECIFIED
}

func (x *NativeEnd) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

var File_api_weir_v1_store_proto protoreflect.FileDescriptor

const file_api_weir_v1_store_proto_rawDesc = "" +
	"\n" +
	"\x17api/weir/v1/store.proto\x12\aweir.v1\"4\n" +
	"\x13ResolveStoreRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\"u\n" +
	"\x14ResolveStoreResponse\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\x12 \n" +
	"\fcache_ttl_ms\x18\x03 \x01(\x04R\n" +
	"cacheTtlMs\"q\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12*\n" +
	"\acommand\x18\x03 \x01(\v2\x10.weir.v1.CommandR\acommand\"M\n" +
	"\x0fExecuteResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12$\n" +
	"\x05event\x18\x02 \x01(\v2\x0e.weir.v1.EventR\x05event\"\xd2\x01\n" +
	"\aCommand\x12*\n" +
	"\x04read\x18\x01 \x01(\v2\x14.weir.v1.ReadRequestH\x00R\x04read\x120\n" +
	"\x06mutate\x18\x02 \x01(\v2\x16.weir.v1.MutateRequestH\x00R\x06mutate\x12*\n" +
	"\x04scan\x18\x03 \x01(\v2\x14.weir.v1.ScanRequestH\x00R\x04scan\x120\n" +
	"\x06native\x18\x04 \x01(\v2\x16.weir.v1.NativeRequestH\x00R\x06nativeB\v\n" +
	"\toperation\"X\n" +
	"\rNativeRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12+\n" +
	"\arequest\x18\x02 \x01(\v2\x11.weir.v1.DocumentR\arequest\"\xe4\x02\n" +
	"\x05Event\x126\n" +
	"\vread_result\x18\x01 \x01(\v2\x13.weir.v1.ReadResultH\x00R\n" +
	"readResult\x12B\n" +
	"\x0fmutation_result\x18\x02 \x01(\v2\x17.weir.v1.MutationResultH\x00R\x0emutationResult\x12/\n" +
	"\bdocument\x18\x03 \x01(\v2\x11.weir.v1.DocumentH\x00R\bdocument\x12)\n" +
	"\x04head\x18\x04 \x01(\v2\x13.weir.v1.NativeHeadH\x00R\x04head\x12\x16\n" +
	"\x05chunk\x18\x05 \x01(\fH\x00R\x05chunk\x12-\n" +
	"\bscan_end\x18\x06 \x01(\v2\x10.weir.v1.ScanEndH\x00R\ascanEnd\x123\n" +
	"\n" +
	"native_end\x18\a \x01(\v2\x12.weir.v1.NativeEndH\x00R\tnativeEndB\a\n" +
	"\x05value\"\a\n" +
	"\x05Empty\"A\n" +
	"\bDocument\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"M\n" +
	"\aFailure\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.weir.v1.FailureCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\vReadRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\"\xa1\x01\n" +
	"\n" +
	"ReadResult\x12/\n" +
	"\bdocument\x18\x01 \x01(\v2\x11.weir.v1.DocumentH\x00R\bdocument\x12*\n" +
	"\amissing\x18\x02 \x01(\v2\x0e.weir.v1.EmptyH\x00R\amissing\x12,\n" +
	"\afailure\x18\x03 \x01(\v2\x10.weir.v1.FailureH\x00R\afailureB\b\n" +
	"\x06result\"\xa3\x02\n" +
	"\rMutateRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12%\n" +
	"\x03put\x18\x02 \x01(\v2\x11.weir.v1.DocumentH\x00R\x03put\x12+\n" +
	"\x06create\x18\x03 \x01(\v2\x11.weir.v1.DocumentH\x00R\x06create\x12-\n" +
	"\areplace\x18\x04 \x01(\v2\x11.weir.v1.DocumentH\x00R\areplace\x12(\n" +
	"\x06delete\x18\x05 \x01(\v2\x0e.weir.v1.EmptyH\x00R\x06delete\x12?\n" +
	"\x10atomic_transform\x18\x06 \x01(\v2\x12.weir.v1.TransformH\x00R\x0fatomicTransformB\b\n" +
	"\x06action\"p\n" +
	"\x0eMutationResult\x122\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x18.weir.v1.MutationOutcomeR\aoutcome\x12*\n" +
	"\afailure\x18\x02 \x01(\v2\x10.weir.v1.FailureR\afailure\"\x82\x01\n" +
	"\tTransform\x12)\n" +
	"\x03lua\x18\x01 \x01(\v2\x15.weir.v1.LuaTransformH\x00R\x03lua\x12B\n" +
	"\x12backend_expression\x18\x02 \x01(\v2\x11.weir.v1.DocumentH\x00R\x11backendExpressionB\x06\n" +
	"\x04form\"O\n" +
	"\fLuaTransform\x12\x16\n" +
	"\x06source\x18\x01 \x01(\fR\x06source\x12'\n" +
	"\x05input\x18\x02 \x01(\v2\x11.weir.v1.DocumentR\x05input\"Q\n" +
	"\n" +
	"Projection\x12+\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x17.weir.v1.ProjectionModeR\x04mode\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"\xd5\x01\n" +
	"\vScanRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12)\n" +
	"\x06filter\x18\x02 \x01(\v2\x11.weir.v1.DocumentR\x06filter\x123\n" +
	"\n" +
	"projection\x18\x03 \x01(\v2\x13.weir.v1.ProjectionR\n" +
	"projection\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\x12-\n" +
	"\x12continuation_token\x18\x05 \x01(\fR\x11continuationToken\"\xb2\x01\n" +
	"\aScanEnd\x12%\n" +
	"\x0edocument_count\x18\x01 \x01(\x04R\rdocumentCount\x12*\n" +
	"\afailure\x18\x02 \x01(\v2\x10.weir.v1.FailureR\afailure\x126\n" +
	"\x17next_continuation_token\x18\x03 \x01(\fR\x15nextContinuationToken\x12\x1c\n" +
	"\texhausted\x18\x04 \x01(\bR\texhausted\"g\n" +
	"\n" +
	"NativeHead\x12-\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.weir.v1.DocumentR\bmetadata\x12*\n" +
	"\x11body_content_type\x18\x02 \x01(\tR\x0fbodyContentType\"r\n" +
	"\tNativeEnd\x129\n" +
	"\n" +
	"completion\x18\x01 \x01(\x0e2\x19.weir.v1.NativeCompletionR\n" +
	"completion\x12*\n" +
	"\afailure\x18\x02 \x01(\v2\x10.weir.v1.FailureR\afailure*\x98\x02\n" +
	"\vFailureCode\x12\x1c\n" +
	"\x18FAILURE_CODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x01\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x02\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x03\x12\x14\n" +
	"\x10TARGET_NOT_FOUND\x10\x04\x12\x17\n" +
	"\x13PRECONDITION_FAILED\x10\x05\x12\f\n" +
	"\bCONFLICT\x10\x06\x12\x0f\n" +
	"\vUNSUPPORTED\x10\a\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\b\x12\x0f\n" +
	"\vUNAVAILABLE\x10\t\x12\r\n" +
	"\tCANCELLED\x10\n" +
	"\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\v\x12\f\n" +
	"\bINTERNAL\x10\f*o\n" +
	"\x0fMutationOutcome\x12 \n" +
	"\x1cMUTATION_OUTCOME_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vNOT_STARTED\x10\x01\x12\x0f\n" +
	"\vNOT_APPLIED\x10\x02\x12\v\n" +
	"\aAPPLIED\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x04*K\n" +
	"\x0eProjectionMode\x12\x1f\n" +
	"\x1bPROJECTION_MODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aINCLUDE\x10\x01\x12\v\n" +
	"\aEXCLUDE\x10\x02*}\n" +
	"\x10NativeCompletion\x12!\n" +
	"\x1dNATIVE_COMPLETION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NATIVE_NOT_STARTED\x10\x01\x12\x15\n" +
	"\x11RESPONSE_COMPLETE\x10\x02\x12\x17\n" +
	"\x13RESPONSE_INCOMPLETE\x10\x032\x9d\x01\n" +
	"\fStoreService\x12K\n" +
	"\fResolveStore\x12\x1c.weir.v1.ResolveStoreRequest\x1a\x1d.weir.v1.ResolveStoreResponse\x12@\n" +
	"\aExecute\x12\x17.weir.v1.ExecuteRequest\x1a\x18.weir.v1.ExecuteResponse(\x010\x01B9Z7github.com/batchstream/weir-protocol/api/weir/v1;weirv1b\x06proto3"

var (
	file_api_weir_v1_store_proto_rawDescOnce sync.Once
	file_api_weir_v1_store_proto_rawDescData []byte
)

func file_api_weir_v1_store_proto_rawDescGZIP() []byte {
	file_api_weir_v1_store_proto_rawDescOnce.Do(func() {
		file_api_weir_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_weir_v1_store_proto_rawDesc), len(file_api_weir_v1_store_proto_rawDesc)))
	})
	return file_api_weir_v1_store_proto_rawDescData
}

var file_api_weir_v1_store_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_weir_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_weir_v1_store_proto_goTypes = []any{
	(FailureCode)(0),             // 0: weir.v1.FailureCode
	(MutationOutcome)(0),         // 1: weir.v1.MutationOutcome
	(ProjectionMode)(0),          // 2: weir.v1.ProjectionMode
	(NativeCompletion)(0),        // 3: weir.v1.NativeCompletion
	(*ResolveStoreRequest)(nil),  // 4: weir.v1.ResolveStoreRequest
	(*ResolveStoreResponse)(nil), // 5: weir.v1.ResolveStoreResponse
	(*ExecuteRequest)(nil),       // 6: weir.v1.ExecuteRequest
	(*ExecuteResponse)(nil),      // 7: weir.v1.ExecuteResponse
	(*Command)(nil),              // 8: weir.v1.Command
	(*NativeRequest)(nil),        // 9: weir.v1.NativeRequest
	(*Event)(nil),                // 10: weir.v1.Event
	(*Empty)(nil),                // 11: weir.v1.Empty
	(*Document)(nil),             // 12: weir.v1.Document
	(*Failure)(nil),              // 13: weir.v1.Failure
	(*ReadRequest)(nil),          // 14: weir.v1.ReadRequest
	(*ReadResult)(nil),           // 15: weir.v1.ReadResult
	(*MutateRequest)(nil),        // 16: weir.v1.MutateRequest
	(*MutationResult)(nil),       // 17: weir.v1.MutationResult
	(*Transform)(nil),            // 18: weir.v1.Transform
	(*LuaTransform)(nil),         // 19: weir.v1.LuaTransform
	(*Projection)(nil),           // 20: weir.v1.Projection
	(*ScanRequest)(nil),          // 21: weir.v1.ScanRequest
	(*ScanEnd)(nil),              // 22: weir.v1.ScanEnd
	(*NativeHead)(nil),           // 23: weir.v1.NativeHead
	(*NativeEnd)(nil),            // 24: weir.v1.NativeEnd
}
var file_api_weir_v1_store_proto_depIdxs = []int32{
	8,  // 0: weir.v1.ExecuteRequest.command:type_name -> weir.v1.Command
	10, // 1: weir.v1.ExecuteResponse.event:type_name -> weir.v1.Event
	14, // 2: weir.v1.Command.read:type_name -> weir.v1.ReadRequest
	16, // 3: weir.v1.Command.mutate:type_name -> weir.v1.MutateRequest
	21, // 4: weir.v1.Command.scan:type_name -> weir.v1.ScanRequest
	9,  // 5: weir.v1.Command.native:type_name -> weir.v1.NativeRequest
	12, // 6: weir.v1.NativeRequest.request:type_name -> weir.v1.Document
	15, // 7: weir.v1.Event.read_result:type_name -> weir.v1.ReadResult
	17, // 8: weir.v1.Event.mutation_result:type_name -> weir.v1.MutationResult
	12, // 9: weir.v1.Event.document:type_name -> weir.v1.Document
	23, // 10: weir.v1.Event.head:type_name -> weir.v1.NativeHead
	22, // 11: weir.v1.Event.scan_end:type_name -> weir.v1.ScanEnd
	24, // 12: weir.v1.Event.native_end:type_name -> weir.v1.NativeEnd
	0,  // 13: weir.v1.Failure.code:type_name -> weir.v1.FailureCode
	12, // 14: weir.v1.ReadResult.document:type_name -> weir.v1.Document
	11, // 15: weir.v1.ReadResult.missing:type_name -> weir.v1.Empty
	13, // 16: weir.v1.ReadResult.failure:type_name -> weir.v1.Failure
	12, // 17: weir.v1.MutateRequest.put:type_name -> weir.v1.Document
	12, // 18: weir.v1.MutateRequest.create:type_name -> weir.v1.Document
	12, // 19: weir.v1.MutateRequest.replace:type_name -> weir.v1.Document
	11, // 20: weir.v1.MutateRequest.delete:type_name -> weir.v1.Empty
	18, // 21: weir.v1.MutateRequest.atomic_transform:type_name -> weir.v1.Transform
	1,  // 22: weir.v1.MutationResult.outcome:type_name -> weir.v1.MutationOutcome
	13, // 23: weir.v1.MutationResult.failure:type_name -> weir.v1.Failure
	19, // 24: weir.v1.Transform.lua:type_name -> weir.v1.LuaTransform
	12, // 25: weir.v1.Transform.backend_expression:type_name -> weir.v1.Document
	12, // 26: weir.v1.LuaTransform.input:type_name -> weir.v1.Document
	2,  // 27: weir.v1.Projection.mode:type_name -> weir.v1.ProjectionMode
	12, // 28: weir.v1.ScanRequest.filter:type_name -> weir.v1.Document
	20, // 29: weir.v1.ScanRequest.projection:type_name -> weir.v1.Projection
	13, // 30: weir.v1.ScanEnd.failure:type_name -> weir.v1.Failure
	12, // 31: weir.v1.NativeHead.metadata:type_name -> weir.v1.Document
	3,  // 32: weir.v1.NativeEnd.completion:type_name -> weir.v1.NativeCompletion
	13, // 33: weir.v1.NativeEnd.failure:type_name -> weir.v1.Failure
	4,  // 34: weir.v1.StoreService.ResolveStore:input_type -> weir.v1.ResolveStoreRequest
	6,  // 35: weir.v1.StoreService.Execute:input_type -> weir.v1.ExecuteRequest
	5,  // 36: weir.v1.StoreService.ResolveStore:output_type -> weir.v1.ResolveStoreResponse
	7,  // 37: weir.v1.StoreService.Execute:output_type -> weir.v1.ExecuteResponse
	36, // [36:38] is the sub-list for method output_type
	34, // [34:36] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_api_weir_v1_store_proto_init() }
func file_api_weir_v1_store_proto_init() {
	if File_api_weir_v1_store_proto != nil {
		return
	}
	file_api_weir_v1_store_proto_msgTypes[4].OneofWrappers = []any{
		(*Command_Read)(nil),
		(*Command_Mutate)(nil),
		(*Command_Scan)(nil),
		(*Command_Native)(nil),
	}
	file_api_weir_v1_store_proto_msgTypes[6].OneofWrappers = []any{
		(*Event_ReadResult)(nil),
		(*Event_MutationResult)(nil),
		(*Event_Document)(nil),
		(*Event_Head)(nil),
		(*Event_Chunk)(nil),
		(*Event_ScanEnd)(nil),
		(*Event_NativeEnd)(nil),
	}
	file_api_weir_v1_store_proto_msgTypes[11].OneofWrappers = []any{
		(*ReadResult_Document)(nil),
		(*ReadResult_Missing)(nil),
		(*ReadResult_Failure)(nil),
	}
	file_api_weir_v1_store_proto_msgTypes[12].OneofWrappers = []any{
		(*MutateRequest_Put)(nil),
		(*MutateRequest_Create)(nil),
		(*MutateRequest_Replace)(nil),
		(*MutateRequest_Delete)(nil),
		(*MutateRequest_AtomicTransform)(nil),
	}
	file_api_weir_v1_store_proto_msgTypes[14].OneofWrappers = []any{
		(*Transform_Lua)(nil),
		(*Transform_BackendExpression)(nil),
	}
	type x struct{}
	packageMarker := x{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(packageMarker).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_weir_v1_store_proto_rawDesc), len(file_api_weir_v1_store_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_weir_v1_store_proto_goTypes,
		DependencyIndexes: file_api_weir_v1_store_proto_depIdxs,
		EnumInfos:         file_api_weir_v1_store_proto_enumTypes,
		MessageInfos:      file_api_weir_v1_store_proto_msgTypes,
	}.Build()
	File_api_weir_v1_store_proto = out.File
	file_api_weir_v1_store_proto_goTypes = nil
	file_api_weir_v1_store_proto_depIdxs = nil
}
